#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-dependency-check-gradle
Version  : 4.0.2
Release  : 1
URL      : https://github.com/jeremylong/dependency-check-gradle/archive/v4.0.2.tar.gz
Source0  : https://github.com/jeremylong/dependency-check-gradle/archive/v4.0.2.tar.gz
Source1  : https://repo.gradle.org/gradle/libs-releases/org/owasp/dependency-check-gradle/4.0.2/dependency-check-gradle-4.0.2.jar
Source2  : https://repo.gradle.org/gradle/libs-releases/org/owasp/dependency-check-gradle/4.0.2/dependency-check-gradle-4.0.2.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-dependency-check-gradle-data = %{version}-%{release}
Requires: mvn-dependency-check-gradle-license = %{version}-%{release}
BuildRequires : buildreq-mvn
BuildRequires : gradle

%description
Dependency-Check-Gradle
=========
[![Build Status](https://travis-ci.org/jeremylong/dependency-check-gradle.svg?branch=master)](https://travis-ci.org/jeremylong/dependency-check-gradle)

%package data
Summary: data components for the mvn-dependency-check-gradle package.
Group: Data

%description data
data components for the mvn-dependency-check-gradle package.


%package license
Summary: license components for the mvn-dependency-check-gradle package.
Group: Default

%description license
license components for the mvn-dependency-check-gradle package.


%prep
%setup -q -n dependency-check-gradle-4.0.2

%build

%install
mkdir -p %{buildroot}/usr/share/package-licenses/mvn-dependency-check-gradle
cp LICENSE.txt %{buildroot}/usr/share/package-licenses/mvn-dependency-check-gradle/LICENSE.txt
cp src/main/resources/META-INF/licenses/gradle/LICENSE.txt %{buildroot}/usr/share/package-licenses/mvn-dependency-check-gradle/src_main_resources_META-INF_licenses_gradle_LICENSE.txt
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/owasp/dependency-check-gradle/4.0.2
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/owasp/dependency-check-gradle/4.0.2/dependency-check-gradle-4.0.2.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/owasp/dependency-check-gradle/4.0.2
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/owasp/dependency-check-gradle/4.0.2/dependency-check-gradle-4.0.2.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/owasp/dependency-check-gradle/4.0.2/dependency-check-gradle-4.0.2.jar
/usr/share/java/.m2/repository/org/owasp/dependency-check-gradle/4.0.2/dependency-check-gradle-4.0.2.pom

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mvn-dependency-check-gradle/LICENSE.txt
/usr/share/package-licenses/mvn-dependency-check-gradle/src_main_resources_META-INF_licenses_gradle_LICENSE.txt
